In [2]:
import numpy as np
zeros_matrix = np.zeros((5, 2))
print(zeros_matrix)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [4]:
array1 = np.linspace(0, 1, 21)
print(array1)

[0.   0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65
 0.7  0.75 0.8  0.85 0.9  0.95 1.  ]


In [5]:
constant_matrix = np.full((5, 2), 3)
print(constant_matrix)

[[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]


In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.arange(4, 28)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27])

In [12]:
np.zeros((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [20]:
np.linspace(10, 25, 2)

array([10, 12, 14, 16, 18, 20, 22, 24])

In [25]:
u = np.array([1, 4, 3, 5])
v = np.array([3, 8, 9, 6])

def vector_vector_multiplication(a, b):
    assert a.shape[0] == b.shape[0] 
    n = a.shape[0]
    result = 0.0
    for i in range(n):
        result +=a[i]*b[i]
    return result

vector_vector_multiplication(u, v)

np.float64(92.0)

In [33]:
u.dot(v)

np.int64(92)

In [28]:
U = np.array([[2, 3, 4, 5], [8, 7, 5, 6], [9, 2, 8, 3]])

def matrix_vector_multiplication(A, b):
    assert A.shape[1] == b.shape[0] 
    n = A.shape[0]
    result = np.zeros(n)
    for i in range(n):
        result[i] += vector_vector_multiplication(A[i], b)
    return result

matrix_vector_multiplication(U, v)

array([ 96., 161., 133.])

In [34]:
U.dot(v)

array([ 96, 161, 133])

In [32]:
V = np.array([[2, 3, 4], [8, 7, 5], [9, 2, 8], [4, 6, 7]])

def matrix_matrix_multiplication(A, B):
    assert A.shape[1] == B.shape[0] 
    n = A.shape[0]
    m = B.shape[1]
    result = np.zeros([n, m])
    for i in range(n):
        for j in range(m):
            result[i][j] += vector_vector_multiplication(A[i], B[:, j])
    return result

matrix_matrix_multiplication(U, V)

array([[ 84.,  65.,  90.],
       [141., 119., 149.],
       [118.,  75., 131.]])

In [35]:
U.dot(V)

array([[ 84,  65,  90],
       [141, 119, 149],
       [118,  75, 131]])